export const GET_CARDS_REQUEST = 'GET_CARDS_REQUEST';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAILURE = 'GET_CARDS_FAILURE';

export const GET_DRAW_CARDS_REQUEST = 'GET_DRAW_CARDS_REQUEST';
export const GET_DRAW_CARDS_SUCCESS = 'GET_DRAW_CARDS_SUCCESS';
export const GET_DRAW_CARDS_FAILURE = 'GET_DRAW_CARDS_FAILURE';

export const HANDLE_ROUND_WINNER = 'HANDLE_ROUND_WINNER';
export const HANDLE_NUMBER_OF_ROUNDS = 'HANDLE_NUMBER_OF_ROUNDS';
export const ADD_SELECTED_CARDS = 'ADD_SELECTED_CARDS';
export const REMOVE_SELECTED_CARDS = 'REMOVE_SELECTED_CARDS';
export const HANDLE_UPDATE_PLAYERS_DECKS = 'HANDLE_UPDATE_PLAYERS_DECKS';
export const HANDLE_GAME_WINNER = 'HANDLE_GAME_WINNER';
